apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostnet
spec:
  selector:
    matchLabels:
      app: hostnet
  replicas: 1
  template:
    metadata:
      labels:
        app: hostnet
    spec:
      hostNetwork: true
      containers:
      - name: net-debug
        image: docker.io/retvari/net-debug